export const CREATE_REQUEST_REQUEST = "CREATE_REQUEST_REQUEST";
export const CREATE_REQUEST_SUCCESS = "CREATE_REQUEST_SUCCESS";
export const CREATE_REQUEST_FAIL = "CREATE_REQUEST_FAIL";

export const MY_REQUESTS_REQUEST = "MY_REQUESTS_REQUEST";
export const MY_REQUESTS_SUCCESS = "MY_REQUESTS_SUCCESS";
export const MY_REQUESTS_FAIL = "MY_REQUESTS_FAIL";

export const ALL_REQUESTS_REQUEST = "ALL_REQUESTS_REQUEST";
export const ALL_REQUESTS_SUCCESS = "ALL_REQUESTS_SUCCESS";
export const ALL_REQUESTS_FAIL = "ALL_REQUESTS_FAIL";

export const UPDATE_REQUEST_REQUEST = "UPDATE_REQUEST_REQUEST";
export const UPDATE_REQUEST_SUCCESS = "UPDATE_REQUEST_SUCCESS";
export const UPDATE_REQUEST_RESET = "UPDATE_REQUEST_RESET";
export const UPDATE_REQUEST_FAIL = "UPDATE_REQUEST_FAIL";

export const DELETE_REQUEST_REQUEST = "DELETE_REQUEST_REQUEST";
export const DELETE_REQUEST_SUCCESS = "DELETE_REQUEST_SUCCESS";
export const DELETE_REQUEST_RESET = "DELETE_REQUEST_RESET";
export const DELETE_REQUEST_FAIL = "DELETE_REQUEST_FAIL";

export const REQUEST_DETAILS_REQUEST = "REQUEST_DETAILS_REQUEST";
export const REQUEST_DETAILS_SUCCESS = "REQUEST_DETAILS_SUCCESS";
export const REQUEST_DETAILS_FAIL = "REQUEST_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
